name: Synch Documentation
on: [push, pull_request]
jobs:
  synch:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
      with:
        path: "aml-workspace"
    
    - name: Check Out Docs Repository
      id: checkout_docs_repository
      uses: actions/checkout@v2
      with:
        repository: "machine-learning-apps/MLOps"
        path: "MLOps"
    
    - name: Copy file to new repo
      run: |
        cp aml-workspace/README.md MLOps/site/docs/aml-workspace.md
        cd MLOps
        git config --local --unset-all "http.https://github.com/.extraheader"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub AML Workspace Action"
        git add .
        git commit -m "Add changes of workspace readme" -a
        git push "https://${{ secrets.GH_TOKEN }}@github.com/machine-learning-apps/MLOps.git" HEAD:master --force
      continue-on-error: true
