name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        id: python_setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v1
      
      - name: Test
        id: python_test
        run: |
          ls
          pip install pytest jsonschema azureml-sdk
          pytest